version: "2"
services:
  app:
    image: golang:1.14.3
    volumes:
        - .:/go/src/poc-docker-compose-aws-reko
    working_dir: /go/src/poc-docker-compose-aws-reko
    command: go run main.go
    environment:
        - AWS_ACCESS_KEY_ID=XXX
        - AWS_SECRET_ACCESS_KEY=XXX